# Generated by Django 3.2.16 on 2023-02-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("metingen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bouwblok",
            fields=[
                (
                    "nummer",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("opmerking", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "aansluitpunt",
                    models.ForeignKey(
                        db_column="aansluitpnt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouwblok_aansluitpunt",
                        to="metingen.hoogtepunt",
                    ),
                ),
                (
                    "controlepunt",
                    models.ForeignKey(
                        db_column="controlepnt",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bouwblok_controlepunt",
                        to="metingen.hoogtepunt",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bouwblokken",
            },
        ),
        migrations.CreateModel(
            name="Referentiepunt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bouwblok",
                    models.ForeignKey(
                        db_column="bou_nummer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bouwblokken.bouwblok",
                    ),
                ),
                (
                    "hoogtepunt",
                    models.ForeignKey(
                        db_column="hoo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metingen.hoogtepunt",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Referentiepunten",
            },
        ),
        migrations.CreateModel(
            name="Kringpunt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("volgorde", models.IntegerField()),
                (
                    "bouwblok",
                    models.ForeignKey(
                        db_column="bou_nummer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bouwblokken.bouwblok",
                    ),
                ),
                (
                    "hoogtepunt",
                    models.ForeignKey(
                        db_column="hoo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metingen.hoogtepunt",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kringpunten",
            },
        ),
        migrations.CreateModel(
            name="Controlepunt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bouwblok",
                    models.ForeignKey(
                        db_column="bou_nummer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controlepunt_bouwblok",
                        to="bouwblokken.bouwblok",
                    ),
                ),
                (
                    "hoogtepunt",
                    models.ForeignKey(
                        db_column="hoo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metingen.hoogtepunt",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Controlepunten",
            },
        ),
    ]
