version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/src
    - ./tests:/tests
    - ./deploy:/deploy
    - /tmp:/src/media
  environment: &base-app-env
    SECRET_KEY: "insecure"
    DEBUG: "true"
    OIDC_BASE_URL: "https://login.microsoftonline.com/72fca1b1-2c2e-4376-a445-294d80196804"
    OIDC_RP_CLIENT_ID:
    OIDC_RP_CLIENT_SECRET:
    APPLICATIONINSIGHTS_CONNECTION_STRING:
  entrypoint: /deploy/wait-for-it.sh database:5432 --

services:
  database:
    image: postgis/postgis:15-3.4
    ports:
      - 5432
    environment:
      POSTGRES_DB: meetbouten
      POSTGRES_USER: meetbouten
      POSTGRES_PASSWORD: insecure
#    volumes:
#      - ./local/csv_dump:/csv_dump
    command: postgres -c datestyle='iso, dmy'

  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: ${REGISTRY:-localhost:5001}/${REPOSITORY:-opdrachten/meetbouten}:${VERSION:-latest}
    command: /deploy/docker-run.sh
      
  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    environment:
      <<: *base-app-env
      DJANGO_SUPERUSER_PASSWORD: "0000"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@amsterdam.nl"
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/meetbouten}-dev:${VERSION:-latest}
    command: python manage.py runserver 0.0.0.0:8000

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-opdrachten/meetbouten}-test:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
      OIDC_RP_CLIENT_ID: tests
      OIDC_RP_CLIENT_SECRET: tests