version: "3.5"

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/src
    - ./tests:/tests
    - ./deploy:/deploy
  environment: &base-app-env
    SECRET_KEY: "insecure"
    DEBUG: "true"
    AUTHORIZATION_TOKEN: "auth-token"
    GET_AUTHORIZATION_TOKEN: "get-auth-token"
  entrypoint: /deploy/wait-for-it.sh database:5432 --

services:
  database:
    image: amsterdam/postgres11
    ports:
      - 5432
    environment:
      POSTGRES_DB: meetbouten
      POSTGRES_USER: meetbouten
      POSTGRES_PASSWORD: insecure

  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: docker-registry.data.amsterdam.nl/datapunt/meetbouten:${VERSION:-latest}
    command: /deploy/docker-run.sh
      
  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    image: 127.0.0.1:5001/meetbouten:${VERSION:-latest}
    command: python manage.py runserver 0.0.0.0:8000

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
