trigger:
  batch: true
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

variables:
  # Debugging
  System.Debug: true

resources:
  repositories:
    - repository: templates
      type: git
      name: opdrachten/templates
      ref: main

extends:
  template: pipelines/aks/template.yaml@templates
  parameters:
    name: meetbouten
    build:
      producedImages:
      - opdrachten/meetbouten-dev
      - opdrachten/meetbouten-test
    dev:
      pool: Opdrachten
      namespace: ns-ccc-opdr-ont-01-meetbouten
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-ont-01-meetbouten"
      preSteps:
        - script: helm uninstall meetbouten -n ns-ccc-opdr-ont-01-meetbouten
    test:
      pool: Opdrachten
      namespace: ns-ccc-opdr-tst-01-meetbouten
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-tst-01-meetbouten"
      preSteps:
        - script: helm uninstall meetbouten -n ns-ccc-opdr-tst-01-meetbouten
    acc:
      pool: Opdrachten
      namespace: ns-ccc-opdr-acc-01-meetbouten
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-acc-01-meetbouten"
    prod:
      pool: Opdrachten
      namespace: ns-ccc-opdr-prd-01-meetbouten
      kubernetesServiceConnection: "SCN-K8S-ns-ccc-opdr-prd-01-meetbouten"