kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: app
  name: app-config
data:
  DATABASE_NAME: "meetbouten"
  DATABASE_USER: "meetbouten"
  DATABASE_PASSWORD: "insecure"
  DATABASE_PORT: "5432"
  POSTGRES_DB: "meetbouten"
  POSTGRES_USER: "meetbouten"
  POSTGRES_PASSWORD: "insecure"
  SECRET_KEY: "insecure"
  DEBUG: "True"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@amsterdam.nl"
  DJANGO_SUPERUSER_PASSWORD: "insecure"