# Generated by Django 3.2.16 on 2023-01-30 08:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouwblok',
            fields=[
                ('nummer', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('opmerking', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bouwblokken',
            },
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=20)),
                ('doel', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Bronnen',
            },
        ),
        migrations.CreateModel(
            name='Hoogtepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.IntegerField()),
                ('agi_nummer', models.CharField(max_length=8)),
                ('vervaldatum', models.DateField(null=True)),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
                ('xmuur', models.FloatField(blank=True, null=True)),
                ('ymuur', models.FloatField(blank=True, null=True)),
                ('windr', models.CharField(max_length=10)),
                ('sigmax', models.FloatField(blank=True, null=True)),
                ('sigmay', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28992)),
                ('orde', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Hoogtepunten',
            },
        ),
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving_verkort', models.CharField(max_length=30)),
                ('omschrijving', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Merken',
            },
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bro_id', models.IntegerField()),
                ('hoogte', models.IntegerField()),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
            options={
                'verbose_name_plural': 'Metingen',
            },
        ),
        migrations.CreateModel(
            name='Metingtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Metingtypes',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Statussen',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('nummer', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=50)),
                ('soort', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='WijzenInwinning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Wijzen inwinning',
            },
        ),
        migrations.CreateModel(
            name='Referentiepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bouwblok', models.ForeignKey(db_column='bou_nummer', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
            options={
                'verbose_name_plural': 'Referentiepunten',
            },
        ),
        migrations.CreateModel(
            name='MetRefPuntenHerz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('meting', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.meting')),
            ],
            options={
                'verbose_name': 'Meting referentiepunten herziening',
                'verbose_name_plural': 'Meting referentiepunten herzieningen',
            },
        ),
        migrations.CreateModel(
            name='MetingReferentiepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('meting', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.meting')),
            ],
            options={
                'verbose_name_plural': 'Meting referentiepunten',
            },
        ),
        migrations.CreateModel(
            name='MetingHerzien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6)),
                ('hoogte', models.IntegerField()),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bron')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('metingtype', models.ForeignKey(db_column='myt_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.metingtype')),
            ],
            options={
                'verbose_name_plural': 'Metingherzieningen',
            },
        ),
        migrations.AddField(
            model_name='meting',
            name='metingtype',
            field=models.ForeignKey(db_column='myt_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.metingtype'),
        ),
        migrations.CreateModel(
            name='Kringpunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volgorde', models.IntegerField()),
                ('bouwblok', models.ForeignKey(db_column='bou_nummer', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
            options={
                'verbose_name_plural': 'Kringpunten',
            },
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='merk',
            field=models.ForeignKey(db_column='mer_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.merk'),
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='status',
            field=models.ForeignKey(db_column='sta_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.status'),
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='type',
            field=models.ForeignKey(db_column='typ_nummer', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type'),
        ),
        migrations.CreateModel(
            name='Grondslagpunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.CharField(max_length=8)),
                ('rdnummer', models.DecimalField(decimal_places=0, max_digits=8)),
                ('orde', models.DecimalField(decimal_places=0, max_digits=1)),
                ('inwindatum', models.DateField()),
                ('vervaldatum', models.DateField()),
                ('wijze_inwinning', models.DecimalField(decimal_places=0, max_digits=1)),
                ('sigmax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sigmay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sigmaz', models.DecimalField(decimal_places=2, max_digits=4)),
                ('omschrijving', models.CharField(blank=True, max_length=256, null=True)),
                ('z', models.IntegerField()),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bron')),
                ('type', models.ForeignKey(db_column='typ_nummer', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type')),
            ],
            options={
                'verbose_name_plural': 'Gronslagpunten',
            },
        ),
        migrations.CreateModel(
            name='Controlepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bouwblok', models.ForeignKey(db_column='bou_nummer', on_delete=django.db.models.deletion.CASCADE, related_name='controlepunt_bouwblok', to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
            options={
                'verbose_name_plural': 'Controlpunten',
            },
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='aansluitpunt',
            field=models.ForeignKey(db_column='aansluitpnt', on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_aansluitpunt', to='meetbouten.hoogtepunt'),
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='controlepunt',
            field=models.ForeignKey(db_column='controlepnt', on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_controlepunt', to='meetbouten.hoogtepunt'),
        ),
    ]
