# Generated by Django 3.2.15 on 2023-01-18 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouwblok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opmerking', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hoogtepunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agi_nummer', models.IntegerField()),
                ('vervaldatum', models.DateField()),
                ('merk', models.IntegerField()),
                ('xmuur', models.FloatField(blank=True, null=True)),
                ('ymuur', models.FloatField(blank=True, null=True)),
                ('windr', models.CharField(max_length=10)),
                ('sigmax', models.FloatField(blank=True, null=True)),
                ('sigmay', models.FloatField(blank=True, null=True)),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
                ('soort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referentiepunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouwblok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwindatum', models.DateField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmaz', models.FloatField(blank=True, null=True)),
                ('bro_id', models.IntegerField()),
                ('bron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bron')),
                ('hoogtepunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.CreateModel(
            name='Kringpunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField()),
                ('bouwblok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type'),
        ),
        migrations.CreateModel(
            name='Grondslagpunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('inwindatum', models.DateField()),
                ('vervaldatum', models.DateField()),
                ('bron', models.IntegerField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmax', models.FloatField(blank=True, null=True)),
                ('sigmay', models.FloatField(blank=True, null=True)),
                ('sigmaz', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type')),
            ],
        ),
        migrations.CreateModel(
            name='Controlepunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouwblok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlepunt_bouwblok', to='meetbouten.bouwblok')),
                ('hoogtepunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='aansluitpunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_aansluitpunt', to='meetbouten.hoogtepunt'),
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='controlepunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_controlepunt', to='meetbouten.hoogtepunt'),
        ),
    ]
