# Generated by Django 3.2.15 on 2023-01-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouwblok',
            fields=[
                ('nummer', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('opmerking', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=20)),
                ('doel', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Hoogtepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.IntegerField()),
                ('agi_nummer', models.IntegerField()),
                ('vervaldatum', models.DateField()),
                ('omschrijving', models.CharField(blank=True, max_length=100, null=True)),
                ('xmuur', models.FloatField(blank=True, null=True)),
                ('ymuur', models.FloatField(blank=True, null=True)),
                ('windr', models.CharField(max_length=10)),
                ('sigmax', models.FloatField(blank=True, null=True)),
                ('sigmay', models.FloatField(blank=True, null=True)),
                ('orde', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving_verkort', models.CharField(max_length=30)),
                ('omschrijving', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bro_id', models.IntegerField()),
                ('hoogte', models.IntegerField()),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.CreateModel(
            name='Metingtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('nummer', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=50)),
                ('soort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WijzenInwinning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('omschrijving', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Referentiepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bou_nummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.CreateModel(
            name='MetRefPuntenHerz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('met_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.meting')),
            ],
        ),
        migrations.CreateModel(
            name='MetingReferentiepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('met_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.meting')),
            ],
        ),
        migrations.CreateModel(
            name='MetingHerzien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('wijze_inwinning', models.IntegerField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6)),
                ('bro_id', models.IntegerField()),
                ('hoogte', models.IntegerField()),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
                ('myt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.metingtype')),
            ],
        ),
        migrations.AddField(
            model_name='meting',
            name='myt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.metingtype'),
        ),
        migrations.CreateModel(
            name='Kringpunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volgorde', models.IntegerField()),
                ('bou_nummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bouwblok')),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='mer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.merk'),
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='sta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.status'),
        ),
        migrations.AddField(
            model_name='hoogtepunt',
            name='typ_nummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type'),
        ),
        migrations.CreateModel(
            name='Grondslagpunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.CharField(max_length=8)),
                ('rdnummer', models.DecimalField(decimal_places=0, max_digits=8)),
                ('orde', models.DecimalField(decimal_places=0, max_digits=1)),
                ('inwindatum', models.DateField()),
                ('vervaldatum', models.DateField()),
                ('wijze_inwinning', models.DecimalField(decimal_places=0, max_digits=1)),
                ('sigmax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sigmay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sigmaz', models.DecimalField(decimal_places=2, max_digits=4)),
                ('omschrijving', models.CharField(blank=True, max_length=256, null=True)),
                ('z', models.IntegerField()),
                ('bro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.bron')),
                ('typ_nummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.type')),
            ],
        ),
        migrations.CreateModel(
            name='Controlepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bou_nummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlepunt_bouwblok', to='meetbouten.bouwblok')),
                ('hoo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetbouten.hoogtepunt')),
            ],
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='aansluitpnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_aansluitpunt', to='meetbouten.hoogtepunt'),
        ),
        migrations.AddField(
            model_name='bouwblok',
            name='controlepnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouwblok_controlepunt', to='meetbouten.hoogtepunt'),
        ),
    ]
