# Generated by Django 3.2.15 on 2023-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetbouten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetbout',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='meetbouten_pictures/'),
        ),
    ]
