tenantId: 72fca1b1-2c2e-4376-a445-294d80196804  # Global

# Default keyvault for getting secrets
keyVaultName: meetbouten-a-6o37eyewduk  # App specific

# Identity AppID (clientId) used to authenticate with the keyvault
workloadIdentity: 90b6b498-daee-4839-9897-e1e253aa12c5  # TODO: Environment specific

# We must select the nodepool to run the pods on
nodepool: cccopdracc01  # Environment specific

# Default host for the ingress resources
host: meetbouten.opdr-a.azure.amsterdam.nl  # App specific

# Some default environment variables to inject in all containers
env:
  AZURE_KEY_VAULT: "https://meetbouten-a-6o37eyewduk.vault.azure.net/"  # App specific
  AZURE_MANAGED_IDENTITY_CLIENTID: 03341363-cc33-4976-ae16-27f763f014fd  # TODO: Environment specific

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-a-uibe5ahqv3cwo  # Environment specific

ingress:
  app:
    className: nginx-internal  # App specific