# Generated by Django 3.2.16 on 2023-02-09 10:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentie_tabellen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoogtepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.CharField(max_length=8)),
                ('agi_nummer', models.CharField(max_length=8, null=True)),
                ('vervaldatum', models.DateField(null=True)),
                ('omschrijving', models.CharField(blank=True, max_length=256, null=True)),
                ('xmuur', models.FloatField(blank=True, null=True)),
                ('ymuur', models.FloatField(blank=True, null=True)),
                ('windr', models.CharField(choices=[('N', 'Noord'), ('NO', 'Noord-Oost'), ('NW', 'Noord-West'), ('O', 'Oost'), ('W', 'West'), ('Z', 'Zuid'), ('ZO', 'Zuid-Oost'), ('ZW', 'Zuid-West')], max_length=2, null=True)),
                ('sigmax', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sigmay', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28992)),
                ('orde', models.IntegerField(null=True)),
                ('merk', models.ForeignKey(db_column='mer_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.merk')),
                ('status', models.ForeignKey(db_column='sta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.status')),
                ('type', models.ForeignKey(db_column='typ_nummer', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.type')),
            ],
            options={
                'verbose_name_plural': 'Hoogtepunten',
            },
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('hoogte', models.FloatField()),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.bron')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.hoogtepunt')),
                ('metingtype', models.ForeignKey(db_column='mty_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.metingtype')),
                ('wijze_inwinning', models.ForeignKey(db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning')),
            ],
            options={
                'verbose_name_plural': 'Metingen',
            },
        ),
        migrations.CreateModel(
            name='MetRefPuntenHerz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.hoogtepunt')),
                ('meting', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.meting')),
            ],
            options={
                'verbose_name': 'Meting referentiepunt herziening',
                'verbose_name_plural': 'Metingen referentiepunten herzieningen',
            },
        ),
        migrations.CreateModel(
            name='MetingReferentiepunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.hoogtepunt')),
                ('meting', models.ForeignKey(db_column='met_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.meting')),
            ],
            options={
                'verbose_name': 'Meting referentiepunt',
                'verbose_name_plural': 'Metingen referentiepunten',
            },
        ),
        migrations.CreateModel(
            name='MetingHerzien',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('sigmaz', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('hoogte', models.FloatField()),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.bron')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.hoogtepunt')),
                ('metingtype', models.ForeignKey(db_column='mty_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.metingtype')),
                ('wijze_inwinning', models.ForeignKey(db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning')),
            ],
            options={
                'verbose_name': 'Meting herziening',
                'verbose_name_plural': 'Metingen herzieningen',
            },
        ),
        migrations.CreateModel(
            name='Grondslagpunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nummer', models.CharField(max_length=8)),
                ('rdnummer', models.DecimalField(decimal_places=0, max_digits=8, null=True)),
                ('orde', models.DecimalField(decimal_places=0, max_digits=1)),
                ('inwindatum', models.DateField()),
                ('vervaldatum', models.DateField(null=True)),
                ('sigmax', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sigmay', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('sigmaz', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28992)),
                ('omschrijving', models.CharField(blank=True, max_length=256, null=True)),
                ('z', models.FloatField(null=True)),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.bron')),
                ('type', models.ForeignKey(db_column='typ_nummer', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.type')),
                ('wijze_inwinning', models.ForeignKey(db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning')),
            ],
            options={
                'verbose_name_plural': 'Gronslagpunten',
            },
        ),
    ]
