# Generated by Django 3.2.16 on 2023-02-09 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metingen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrefpuntenherz",
            name="meting",
            field=models.ForeignKey(
                db_column="met_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="metingen.metingherzien",
            ),
        ),
    ]
