# Generated by Django 3.2.16 on 2023-02-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referentie_tabellen', '0002_seed_static_tables'),
        ('metingen', '0002_alter_metrefpuntenherz_meting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grondslagpunt',
            options={'verbose_name_plural': 'Grondslagpunten'},
        ),
        migrations.AlterModelOptions(
            name='meting',
            options={'verbose_name': 'Meting [Archief tm 2009]', 'verbose_name_plural': 'Metingen [Archief tm 2009]'},
        ),
        migrations.AlterModelOptions(
            name='metingherzien',
            options={'verbose_name': 'Meting [Herzien]', 'verbose_name_plural': 'Metingen [Herzien]'},
        ),
        migrations.AlterModelOptions(
            name='metingreferentiepunt',
            options={'verbose_name': 'Referentiepunt [Archief tm 2009]', 'verbose_name_plural': 'Referentiepunten [Archief tm 2009]'},
        ),
        migrations.AlterModelOptions(
            name='metrefpuntenherz',
            options={'verbose_name': 'Referentiepunt [Herzien]', 'verbose_name_plural': 'Referentiepunten [Herzien]'},
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='rdnummer',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='sigmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='sigmay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='sigmaz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='vervaldatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='wijze_inwinning',
            field=models.ForeignKey(blank=True, db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning'),
        ),
        migrations.AlterField(
            model_name='grondslagpunt',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='agi_nummer',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='orde',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='sigmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='sigmay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='status',
            field=models.ForeignKey(blank=True, db_column='sta_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.status'),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='vervaldatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoogtepunt',
            name='windr',
            field=models.CharField(blank=True, choices=[('N', 'Noord'), ('NO', 'Noord-Oost'), ('NW', 'Noord-West'), ('O', 'Oost'), ('W', 'West'), ('Z', 'Zuid'), ('ZO', 'Zuid-Oost'), ('ZW', 'Zuid-West')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='meting',
            name='sigmaz',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='meting',
            name='wijze_inwinning',
            field=models.ForeignKey(blank=True, db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning'),
        ),
        migrations.AlterField(
            model_name='metingherzien',
            name='sigmaz',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='metingherzien',
            name='wijze_inwinning',
            field=models.ForeignKey(blank=True, db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning'),
        ),
    ]
