# Generated by Django 3.2.18 on 2023-02-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referentie_tabellen', '0002_seed_static_tables'),
        ('metingen', '0004_createcachetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metingherzien',
            options={'verbose_name': 'Meting', 'verbose_name_plural': 'Metingen'},
        ),
        migrations.AlterModelOptions(
            name='metrefpuntenherz',
            options={'verbose_name': 'Referentiepunt', 'verbose_name_plural': 'Referentiepunten'},
        ),
        migrations.CreateModel(
            name='MetingControle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inwindatum', models.DateField()),
                ('sigmaz', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('hoogte', models.FloatField()),
                ('bron', models.ForeignKey(db_column='bro_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.bron')),
                ('hoogtepunt', models.ForeignKey(db_column='hoo_id', on_delete=django.db.models.deletion.CASCADE, to='metingen.hoogtepunt')),
                ('metingtype', models.ForeignKey(db_column='mty_id', on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.metingtype')),
                ('wijze_inwinning', models.ForeignKey(blank=True, db_column='wijze_inwinning', null=True, on_delete=django.db.models.deletion.CASCADE, to='referentie_tabellen.wijzeninwinning')),
            ],
            options={
                'verbose_name': 'Meting [ter controle]',
                'verbose_name_plural': 'Metingen [ter contole]',
            },
        ),
    ]
