# Generated by Django 3.2.18 on 2023-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metingen", "0005_auto_20230228_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoogtepunt",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="meetbouten_pictures/"
            ),
        ),
    ]
