# Generated by Django 3.2.18 on 2023-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0007_auto_20230321_1154'),
        ('metingen', '0007_metingverrijking'),
    ]

    operations = [
    ]
