# Generated by Django 3.2.18 on 2023-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metingen", "0008_merge_0007_auto_20230321_1154_0007_metingverrijking"),
    ]

    operations = [
        migrations.AddField(
            model_name="metingverrijking",
            name="file_name",
            field=models.CharField(default="file.tco", max_length=60),
            preserve_default=False,
        ),
    ]
