# Generated by Django 3.2.18 on 2023-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metingen", "0009_metingverrijking_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meting",
            name="hoogte",
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name="metingcontrole",
            name="hoogte",
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name="metingherzien",
            name="hoogte",
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name="metingverrijking",
            name="hoogte",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=6, null=True
            ),
        ),
    ]
