# Generated by Django 4.1.12 on 2023-11-15 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metingen", "0011_alter_grondslagpunt_bron_alter_grondslagpunt_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metingherzien",
            options={
                "get_latest_by": "inwindatum",
                "verbose_name": "Meting",
                "verbose_name_plural": "Metingen",
            },
        ),
    ]
