# Generated by Django 5.1.5 on 2025-02-25 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metingen', '0012_alter_metingherzien_options'),
        ('referentie_tabellen', '0002_seed_static_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoogtepunt',
            name='status',
            field=models.ForeignKey(db_column='sta_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='referentie_tabellen.status'),
        ),
    ]
