name: Opdrachten Team Dependabot

on:
  schedule: # Run the script on the 1st and 15th of every month
    - cron: '0 6 1 * *'
  workflow_dispatch:


jobs:
  dependabot:
    name: Templates
    uses: amsterdam/github-workflows/.github/workflows/dependabot.yml@v1
    secrets: inherit
    with:
      check_diff: true
      slack_channel: 'opdrachten-dependabot'
      timetell_code: 0000
      acceptance_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=2067"
      production_pipeline: "https://dev.azure.com/CloudCompetenceCenter/Opdrachten/_build?definitionId=2067"
      acceptance_urls: "https://acc.meetbouten.amsterdam.nl/"
      production_urls: "https://meetbouten.amsterdam.nl/"

