name: Opdrachten Team Dependabot

on:
  pull_request:
    branches: main

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Update dependencies
      run: make requirements

    - name: Set up Docker Buildx for Docker build caching
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/amsterdam/meetbouten:latest

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Get current date
      id: date
      run: echo "{date}=$(date +'%Y-%m-%d')" >>  $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Updated dependencies
        committer: Opdrachten Team Dependabot <opdrachten-team-dependabot@amsterdam.nl>
        body: |
          New report
          - Contains *today's* date
          - Auto-generated by [create-pull-request][1]
  
          [1]: https://github.com/peter-evans/create-pull-request
        title: 'Maintenance run ${{ steps.date.outputs.date }}'
        labels: Opdrachten Team Dependabot
        branch: example-patches

    - uses: someimportantcompany/github-actions-slack-message@v1
      with:
        channel: ${{ env.SLACK_CHANNEL }}
        bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
        text: Firing a bot-token message