name: Opdrachten Team Dependabot

on:
  pull_request:
    branches: main

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.today }}
    steps:
#    - uses: actions/checkout@v3
#      with:
#        ref: main
#
#    - name: Login to GitHub Container Registry
#      uses: docker/login-action@v2
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
#
#    - name: Set up Docker Buildx for Docker build caching
#      uses: docker/setup-buildx-action@v2
#
#    - name: Update dependencies
#      run: make requirements
#
#    - name: Build and push
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: true
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
#        tags: ghcr.io/amsterdam/meetbouten:latest
#
#    - name: Test
#      run: make test
#
#    - name: Get current date
#      id: date
#      run: echo "today=$(date +'%Y-%m-%d')" >>  $GITHUB_OUTPUT
#
#    - name: Print current date
#      run: echo "Today is ${{ steps.date.outputs.today }}"
#
#    - name: Create Pull Request on date with current date as title
#      uses: peter-evans/create-pull-request@v5
#      with:
#        title: 'Maintenance run ${{ steps.date.outputs.today }}'
#        labels: Opdrachten Team Dependabot
#        body: |
#          Auto generated PR to update dependencies.
#          This PR is generated by the Opdrachten Team Dependabot
#        branch: dependabot/${{ steps.date.outputs.today }}
#        committer: Opdrachten Team Dependabot <opdrachten-team-dependabot@amsterdam.nl>
#        commit-message: 'Maintenance run ${{ steps.date.outputs.today }}'

    - uses: someimportantcompany/github-actions-slack-message@v1
      with:
        channel: opdrachten-backend
        bot-token: xoxb-6265386162-3073554450099-P9fvqMx1e3GMCyjEsBvRyhmC
        text: Firing a bot-token message from Github Actions