name: Opdrachten Team Dependabot

on:
  pull_request:
    branches: main

jobs:
  dependabot:
    name: Update dependencies
    uses: amsterdam/opdrachten-team-github-workflows/.github/workflows/dependabot.yml@v1

