name: Opdrachten Team Dependabot

on:
  schedule: # Run the script every day at 6am UTC
    - cron: "0 6 * * *"
  workflow_dispatch:


jobs:
  dependabot:
    name: Templates
    uses: amsterdam/github-workflows/.github/workflows/dependabot.yml@v1
    secrets: inherit
    with:
      check_diff: true
      slack_channel: 'opdrachten-dependabot'
      timetell_code: 21127
      acceptance_pipeline: "https://ci.secure.amsterdam.nl/job/Opdrachten/job/Quotumtool/job/Quotumtool/job/main/"
      production_pipeline: "https://ci.secure.amsterdam.nl/job/Opdrachten/job/Quotumtool/job/Quotumtool/view/tags/"
      acceptance_urls: "https://acc.api.secure.amsterdam.nl/vergunningen/quota/kameromzettingen/dashboard/ \n
      https://acc.api.secure.amsterdam.nl/vergunningen/quota/bb/dashboard/"
      production_urls: "https://api.secure.amsterdam.nl/vergunningen/quota/kameromzettingen/dashboard/ \n
      https://api.secure.amsterdam.nl/vergunningen/quota/bb/dashboard/"

